version: '3'

services:
  node:
    build:
        context: .
        dockerfile: node.dockerfile
    image: node-app/node-image
    container_name: bd-node-app
    environment:
      NODE_ENV: development
    networks:
      - backend
    volumes:
      - .:/bd-node-app
    ports:
      - 5555:5555
    command: nodemon server.js
    depends_on:
     - postgres

  postgres:
    expose:
      - "5432"
    image: postgres:11-alpine
    container_name: bd-postgres-app
    networks:
      - backend
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: projetobd
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: projetobd
      POSTGRES_HOST: postgres
      PGDATA: /var/lib/postgresql/data
    # volumes:
      # - ./sql:/projetobd
      # - ./postgres-data:/var/lib/postgresql/data
      # - ./sql:/docker-entrypoint-initdb.d/

networks:
  backend:
    driver: bridge
